const currentYear = new Date().getFullYear().toString();

const CATEGORY_SEARCHES = {
  tech: {
    prefixes: [
      "review of",
      "best price for",
      "issues with",
      "specs for",
      "release date of",
      "problems with",
      "guide to",
      "is it worth buying",
      "latest news about",
      "comparison of",
      "deals on",
    ],
    topics: [
      "rtx 5090",
      "rtx 4090",
      "ps5",
      "xbox series x",
      "samsung galaxy",
      "google pixel",
      "iphone",
      "ipad pro",
      "macbook air",
      "mac mini",
      "tesla",
      "windows 11",
      "mechanical keyboard",
      "gaming monitor",
      "sony headphones",
      "airpods pro",
      "apple watch ultra",
      "steam deck",
      "gaming laptop",
      "dell xps",
      "asus rog",
      "lenovo thinkpad",
      "kindle",
      "gopro",
      "bluetooth speaker",
      "wifi 7 router",
      "samsung oled tv",
    ],
    suffixes: [
      currentYear,
      "reddit",
      "youtube",
      "benchmark",
      "rumors",
      "review",
      "specs",
      "official site",
      "driver update",
      "on sale",
      "unboxing",
    ],
  },

  coding: {
    prefixes: [
      "how to use",
      "tutorial for",
      "setup guide for",
      "fix error in",
      "example of",
      "documentation for",
      "alternatives to",
      "learn",
      "course for",
      "best tools for",
    ],
    topics: [
      "node js",
      "react hooks",
      "javascript array",
      "css flexbox",
      "typescript types",
      "sql query",
      "python pandas",
      "git commands",
      "docker containers",
      "linux ubuntu",
      "mongodb",
      "aws s3",
      "next js",
      "rust",
      "go lang",
      "flutter",
      "vscode",
      "npm",
    ],
    suffixes: [
      "example",
      "stackoverflow",
      "tutorial",
      "crash course",
      "cheatsheet",
      "github",
      "docs",
      "explained",
      "for beginners",
      "best practices",
    ],
  },

  education: {
    prefixes: [
      "definition of",
      "facts about",
      "history of",
      "meaning of",
      "timeline of",
      "summary of",
      "guide to",
      "explained",
      "basics of",
    ],
    topics: [
      "periodic table",
      "photosynthesis",
      "dna replication",
      "pythagorean theorem",
      "solar system",
      "black holes",
      "speed of light",
      "civil war",
      "world war 2",
      "french revolution",
      "ancient egypt",
      "greek mythology",
      "shakespeare",
      "climate change",
      "water cycle",
      "human anatomy",
      "quantum physics",
    ],
    suffixes: [
      "wiki",
      "quiz",
      "worksheet",
      "images",
      "video",
      "dates",
      "summary",
      "explained",
      "presentation",
      "article",
    ],
  },

  movies: {
    prefixes: [
      "top 10",
      "best",
      "new",
      "upcoming",
      "cast of",
      "ending of",
      "watch",
      "review of",
      "sequel to",
      "rating for",
    ],
    topics: [
      "sci fi movies",
      "horror movies",
      "action movies",
      "anime series",
      "marvel movies",
      "star wars",
      "harry potter",
      "lord of the rings",
      "game of thrones",
      "stranger things",
      "breaking bad",
      "the office",
      "friends show",
      "batman movies",
      "spiderman movies",
    ],
    suffixes: [
      "trailer",
      "streaming",
      "release date",
      "explained",
      "imdb",
      "rotten tomatoes",
      "season 2",
      "soundtrack",
      "poster",
      "full movie",
    ],
  },

  people: {
    prefixes: [
      "who is",
      "how old is",
      "net worth of",
      "height of",
      "who is dating",
      "movies with",
      "songs by",
      "latest news on",
      "biography of",
      "where does live",
      "is married",
    ],
    topics: [
      "elon musk",
      "lionel messi",
      "taylor swift",
      "wayne johnson",
      "selena gomez",
      "kylie jenner",
      "kim kardashian",
      "justin bieber",
      "beyonce",
      "tom cruise",
      "robert downey jr",
      "keanu reeves",
      "zendaya",
      "tom holland",
      "ryan reynolds",
      "scarlett johansson",
      "lebron james",
      "conor mcgregor",
      "cristiano ronaldo",
      "virat kohli",
      "mr beast",
      "billie eilish",
      "drake",
      "eminem",
      "ariana grande",
      "rihanna",
      "mark zuckerberg",
      "jeff bezos",
      "barack obama",
      "donald trump",
    ],
    suffixes: [
      currentYear,
      "instagram",
      "twitter",
      "net worth",
      "news",
      "interview",
      "memes",
      "family",
      "wife",
      "husband",
      "movies",
      "songs",
    ],
  },

  gaming: {
    prefixes: [
      "best",
      "guide to",
      "review of",
      "release date of",
      "tips for",
      "cheats for",
      "how to play",
      "mods for",
    ],
    topics: [
      "rdr 2",
      "gta 6",
      "gta 4",
      "valorant",
      "league of legends",
      "cyberpunk 2077",
      "minecraft",
      "fortnite",
      "roblox",
      "cod",
      "forza horizon 5",
      "spiderman remastered",
      "god of war",
      "ghost of tsushima",
      "last of us",
      "farcry 6",
      "overwatch 2",
      "witcher 3",
      "sims 4",
      "resident evil",
      "tomb raider",
      "metal gear solid",
      "bat man arkham knight",
      "assassin's creed",
      "alan wake 2",
      "hogwarts legacy",
      "black myth wukong",
      "battlefield 6",
    ],
    suffixes: [
      "gameplay",
      "update",
      "wiki",
      "review",
      "reddit",
      "ign",
      "metacritic",
      "discord",
      "requirements",
      "twitch",
      "wallpaper",
    ],
  },

  local: {
    prefixes: [
      "best",
      "cheap",
      "nearest",
      "top rated",
      "24 hour",
      "open",
      "affordable",
      "reviews for",
      "phone number for",
      "directions to",
    ],
    topics: [
      "pizza delivery",
      "chinese food",
      "sushi",
      "tacos",
      "restaurants",
      "coffee shop",
      "bakery",
      "pharmacy",
      "hospital",
      "gym",
      "yoga studio",
      "barber shop",
      "hair salon",
      "nail salon",
      "dry cleaners",
      "mechanic",
      "car wash",
      "dentist",
      "vet",
      "florist",
      "plumber",
      "electrician",
    ],
    suffixes: [
      "near me",
      "nearby",
      "open now",
      "closest",
      "reviews",
      "prices",
      "menu",
      "phone number",
      "hours",
    ],
  },

  lifestyle: {
    prefixes: [
      "benefits of",
      "how to start",
      "tips for",
      "guide to",
      "routines for",
      "best gear for",
      "mistakes in",
      "ideas for",
      "tutorial for",
    ],
    topics: [
      "yoga",
      "meditation",
      "keto diet",
      "intermittent fasting",
      "calisthenics",
      "marathon training",
      "gardening",
      "indoor plants",
      "knitting",
      "sketching",
      "photography",
      "learning guitar",
      "learning piano",
    ],
    suffixes: [
      "for beginners",
      "at home",
      "routine",
      "plan",
      "results",
      "app",
      "course",
      "blog",
      "pdf",
    ],
  },

  food: {
    prefixes: [
      "recipe for",
      "how to cook",
      "ingredients in",
      "calories in",
      "best way to make",
      "easy",
      "healthy",
      "authentic",
    ],
    topics: [
      "sourdough bread",
      "banana bread",
      "chocolate chip cookies",
      "pancakes",
      "waffles",
      "pasta carbonara",
      "lasagna",
      "pizza dough",
      "tacos",
      "guacamole",
      "chicken curry",
      "pad thai",
      "ramen",
      "burger",
      "cheesecake",
    ],
    suffixes: [
      "recipe",
      "easy",
      "video",
      "step by step",
      "ingredients",
      "without eggs",
      "in air fryer",
      "slow cooker",
    ],
  },

  travel: {
    prefixes: [
      "best time to visit",
      "flights to",
      "hotels in",
      "things to do in",
      "guide to",
      "budget for",
      "map of",
      "tours in",
    ],
    topics: [
      "tokyo",
      "paris",
      "london",
      "rome",
      "new york",
      "los angeles",
      "hawaii",
      "bali",
      "thailand",
      "iceland",
      "switzerland",
      "disneyland",
    ],
    suffixes: [
      "tripadvisor",
      "itinerary",
      "budget",
      "with family",
      "images",
      "reviews",
      "packages",
      "cost",
    ],
  },
};

const COMMON_SEARCHES = [
  "weather",
  "weather tomorrow",
  "news",
  "google maps",
  "gmail",
  "translate",
  "calculator",
  "calendar",
  "timer",
  "stopwatch",
  "alarm",
  "speed test",
  "my ip",
  "date today",
  "week number",
  "currency converter",
  "usd to inr",
  "eur to inr",
  "qr code generator",
  "color picker",
  "periodic table",

  "facebook",
  "instagram",
  "twitter",
  "x login",
  "reddit",
  "linkedin",
  "pinterest",
  "whatsapp web",
  "discord",
  "telegram web",
  "tiktok",
  "snapchat",
  "quora",
  "skype",
  "zoom login",
  "slack",

  "youtube",
  "yt music",
  "spotify",
  "netflix",
  "twitch",
  "hulu",
  "disney plus",
  "prime video",
  "hbo max",
  "imdb",
  "rotten tomatoes",
  "ign",
  "espn",
  "nba scores",
  "premier league table",
  "f1 schedule",
  "bbc",
  "cnn",
  "fox news",

  "amazon",
  "flipkart",
  "nike",
  "adidas",
  "apple store",
  "samsung",

  "chatgpt",
  "gemini",
  "wikipedia",
  "github",
  "stackoverflow",
  "google drive",
  "google docs",
  "microsoft 365",
  "canva",
  "notion",
  "adobe",
  "dropbox",
  "indeed",
  "glassdoor",
  "coursera",
  "udemy",

  "bitcoin price",
  "ethereum price",
  "stock market",
  "gold price",
  "crypto prices",
  "tax calculator",

  "google flights",
  "skyscanner",
  "airbnb",
  "booking.com",
  "hotels",
  "uber eats",
  "zomato",
  "blinkit",
  "swiggy",
  "dominos",
  "pizza hut",
  "starbucks",
  "mcdonalds menu",
  "restaurants near me",

  "wordle hint",
  "connections hint",
  "daily crossword",
  "sudoku",
  "solitaire",
  "snake game",
  "pacman",
  "tic tac toe",
  "online games",
  "flip coin",
  "roll die",
  "random number generator",
  "fun facts",
  "jokes",
];

export { CATEGORY_SEARCHES, COMMON_SEARCHES };
